"""Combined ModularBooth loss with configurable component weights.

This module provides :class:`ModularBoothLoss`, the top-level loss used during
training.  It aggregates three components:

1. **Diffusion loss** -- standard MSE between the model's noise prediction and
   the ground-truth noise target on subject images.
2. **Prior Preservation Loss (PPL)** -- MSE on class-prior images generated by
   the frozen base model, preventing language drift.
3. **Contrastive Context Disentanglement (CCD) loss** -- InfoNCE contrastive
   objective on intermediate DiT features that encourages the model to separate
   subject identity from background context.

CCD is optional: it is only computed when intermediate features are provided
*and* the current training step exceeds a configurable warm-up period.  During
warm-up the CCD weight ramps linearly from 0 to ``lambda_ccd`` so the
contrastive signal does not destabilise early diffusion-loss convergence.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import torch
import torch.nn as nn

from modularbooth.losses.ccd_loss import CCDLoss
from modularbooth.losses.prior_preservation import PriorPreservationLoss


class ModularBoothLoss(nn.Module):
    """Unified loss combining diffusion, prior-preservation, and CCD terms.

    Args:
        lambda_ppl: Weight for the prior preservation loss.
        lambda_ccd: Maximum weight for the CCD contrastive loss (reached
            after warm-up completes).
        ccd_warmup_steps: Number of training steps during which CCD is
            either disabled or linearly ramped up.  CCD loss is not
            computed at all before this step, giving the diffusion
            objective time to stabilise.
        ccd_temperature: Temperature parameter forwarded to
            :class:`CCDLoss`.
        ccd_feature_dim: Optional projection dimension forwarded to
            :class:`CCDLoss`.
    """

    def __init__(
        self,
        lambda_ppl: float = 1.0,
        lambda_ccd: float = 0.3,
        ccd_warmup_steps: int = 100,
        ccd_temperature: float = 0.07,
        ccd_feature_dim: Optional[int] = None,
    ) -> None:
        super().__init__()
        if lambda_ppl < 0:
            raise ValueError(f"lambda_ppl must be non-negative, got {lambda_ppl}")
        if lambda_ccd < 0:
            raise ValueError(f"lambda_ccd must be non-negative, got {lambda_ccd}")
        if ccd_warmup_steps < 0:
            raise ValueError(
                f"ccd_warmup_steps must be non-negative, got {ccd_warmup_steps}"
            )

        self.lambda_ppl = lambda_ppl
        self.lambda_ccd = lambda_ccd
        self.ccd_warmup_steps = ccd_warmup_steps

        self.ppl = PriorPreservationLoss(lambda_ppl=lambda_ppl)
        self.ccd = CCDLoss(
            temperature=ccd_temperature,
            feature_dim=ccd_feature_dim,
        )

    # ------------------------------------------------------------------
    # Public helpers
    # ------------------------------------------------------------------

    def get_loss_weights(self, global_step: int) -> Dict[str, float]:
        """Return the effective weight of each loss component at *global_step*.

        This is primarily useful for logging and learning-rate / loss-weight
        schedules.

        Args:
            global_step: Current training step (zero-indexed).

        Returns:
            Dictionary with keys ``"diffusion"``, ``"ppl"``, and ``"ccd"``,
            mapping to the scalar weight applied to each loss term.
        """
        ccd_weight = self._effective_ccd_weight(global_step)
        return {
            "diffusion": 1.0,
            "ppl": self.lambda_ppl,
            "ccd": ccd_weight,
        }

    # ------------------------------------------------------------------
    # Forward
    # ------------------------------------------------------------------

    def forward(
        self,
        model_pred_subject: torch.Tensor,
        noise_target_subject: torch.Tensor,
        model_pred_class: torch.Tensor,
        noise_target_class: torch.Tensor,
        subject_features: Optional[torch.Tensor] = None,
        positive_features: Optional[torch.Tensor] = None,
        negative_features: Optional[torch.Tensor] = None,
        global_step: int = 0,
    ) -> Dict[str, Any]:
        """Compute the combined ModularBooth loss.

        Args:
            model_pred_subject: Noise prediction for subject images.
            noise_target_subject: Ground-truth noise for subject images.
            model_pred_class: Noise prediction for class-prior images.
            noise_target_class: Ground-truth noise for class-prior images.
            subject_features: ``(B, D)`` subject anchor features for CCD.
                If ``None``, CCD loss is skipped.
            positive_features: ``(B, D)`` positive features for CCD.
                If ``None``, CCD loss is skipped.
            negative_features: ``(B, N_neg, D)`` negative features for CCD.
                If ``None``, CCD loss is skipped.
            global_step: Current training step, used to determine whether
                CCD warm-up has elapsed.

        Returns:
            Dictionary containing:

            - ``"total_loss"`` -- scalar tensor for back-propagation.
            - ``"diffusion_loss"`` -- unweighted subject diffusion loss.
            - ``"ppl_loss"`` -- weighted prior preservation loss.
            - ``"ccd_loss"`` -- weighted CCD loss (``0`` if not computed).
            - ``"loss_components"`` -- nested dict of raw (unweighted)
              component values suitable for logging.
        """
        # ---- Diffusion + Prior Preservation ----
        diffusion_loss, ppl_loss = self.ppl(
            model_pred_subject,
            noise_target_subject,
            model_pred_class,
            noise_target_class,
        )

        total_loss = diffusion_loss + ppl_loss

        # ---- CCD (optional) ----
        ccd_features_available = (
            subject_features is not None
            and positive_features is not None
            and negative_features is not None
        )
        compute_ccd = ccd_features_available and global_step >= self.ccd_warmup_steps

        if compute_ccd:
            assert subject_features is not None  # satisfy type checker
            assert positive_features is not None
            assert negative_features is not None

            raw_ccd_loss = self.ccd(subject_features, positive_features, negative_features)
            effective_ccd_weight = self._effective_ccd_weight(global_step)
            weighted_ccd_loss = effective_ccd_weight * raw_ccd_loss
            total_loss = total_loss + weighted_ccd_loss
        else:
            device = diffusion_loss.device
            raw_ccd_loss = torch.tensor(0.0, device=device)
            weighted_ccd_loss = torch.tensor(0.0, device=device)

        return {
            "total_loss": total_loss,
            "diffusion_loss": diffusion_loss,
            "ppl_loss": ppl_loss,
            "ccd_loss": weighted_ccd_loss,
            "loss_components": {
                "diffusion_loss_raw": diffusion_loss.item(),
                "ppl_loss_raw": (ppl_loss / self.lambda_ppl).item() if self.lambda_ppl > 0 else 0.0,
                "ppl_loss_weighted": ppl_loss.item(),
                "ccd_loss_raw": raw_ccd_loss.item(),
                "ccd_loss_weighted": weighted_ccd_loss.item(),
                "ccd_weight_effective": self._effective_ccd_weight(global_step),
                "total_loss": total_loss.item(),
            },
        }

    # ------------------------------------------------------------------
    # Private
    # ------------------------------------------------------------------

    def _effective_ccd_weight(self, global_step: int) -> float:
        """Compute the effective CCD weight accounting for warm-up.

        Before ``ccd_warmup_steps`` the weight is 0.  After warm-up completes
        the weight equals ``lambda_ccd``.  There is no linear ramp *during*
        warm-up -- CCD is simply disabled until the diffusion objective has
        stabilised, then it is enabled at full strength.  A ramp can be added
        here in the future if experiments show it helps.

        Args:
            global_step: Current training step.

        Returns:
            Effective scalar weight for the CCD loss.
        """
        if global_step < self.ccd_warmup_steps:
            return 0.0
        return self.lambda_ccd
