"""Prior Preservation Loss from DreamBooth.

This module implements the prior preservation loss (PPL) introduced in the
DreamBooth paper (Ruiz et al., 2023).  During fine-tuning the diffusion model
is trained on both *subject* images (with a unique identifier) and *class*
images generated by the frozen base model.  The class-image loss acts as a
regulariser that prevents language drift and mode collapse.

Additionally, a standalone utility function ``generate_class_images`` is
provided to pre-generate the class-prior dataset using the frozen pipeline.
"""

from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import Any, Union

import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger(__name__)


class PriorPreservationLoss(nn.Module):
    """Prior Preservation Loss for DreamBooth-style fine-tuning.

    Computes separate MSE losses for subject and class (prior-preservation)
    predictions and returns them as a tuple so callers can log and weight
    them independently.

    Args:
        lambda_ppl: Scalar weight applied to the class (prior preservation)
            loss.  A value of 1.0 weights it equally with the subject loss.
    """

    def __init__(self, lambda_ppl: float = 1.0) -> None:
        super().__init__()
        if lambda_ppl < 0:
            raise ValueError(f"lambda_ppl must be non-negative, got {lambda_ppl}")
        self.lambda_ppl = lambda_ppl

    def forward(
        self,
        model_pred_subject: torch.Tensor,
        noise_target_subject: torch.Tensor,
        model_pred_class: torch.Tensor,
        noise_target_class: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Compute diffusion MSE losses for subject and class samples.

        Args:
            model_pred_subject: Model noise prediction for subject images.
            noise_target_subject: Ground-truth noise target for subject images.
            model_pred_class: Model noise prediction for class-prior images.
            noise_target_class: Ground-truth noise target for class-prior
                images.

        Returns:
            A tuple ``(subject_loss, weighted_class_loss)`` where
            ``weighted_class_loss = lambda_ppl * class_mse``.  Both are scalar
            tensors suitable for back-propagation.
        """
        subject_loss = F.mse_loss(model_pred_subject, noise_target_subject)
        class_loss = F.mse_loss(model_pred_class, noise_target_class)
        return subject_loss, self.lambda_ppl * class_loss


def generate_class_images(
    pipeline: Any,
    class_prompt: str,
    num_images: int,
    output_dir: str,
    *,
    batch_size: int = 4,
    num_inference_steps: int = 50,
    guidance_scale: float = 7.5,
    seed: int = 0,
) -> list[str]:
    """Generate class-prior images using a frozen diffusion pipeline.

    This function produces the dataset of class images required by the prior
    preservation loss.  It should be called **once** before training begins,
    using the *base* (un-fine-tuned) model.

    Args:
        pipeline: A diffusion pipeline object (e.g.
            ``diffusers.DiffusionPipeline``) that accepts a ``prompt``
            argument and returns an object with an ``images`` attribute.
            The pipeline is used in inference mode; no gradients are
            computed.
        class_prompt: The text prompt describing the class (e.g.
            ``"a photo of a dog"``).
        num_images: Total number of class images to generate.
        output_dir: Directory where the generated images will be saved as
            PNG files.
        batch_size: Number of images to generate per pipeline call.
        num_inference_steps: Denoising steps per image.
        guidance_scale: Classifier-free guidance scale.
        seed: Base random seed for reproducibility.  Each batch uses
            ``seed + batch_index`` to ensure unique but deterministic
            outputs.

    Returns:
        List of absolute file paths to the generated images.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    # Check how many images already exist so we can skip regeneration.
    existing = sorted(output_path.glob("class_*.png"))
    if len(existing) >= num_images:
        logger.info(
            "Found %d existing class images in %s (need %d); skipping generation.",
            len(existing),
            output_dir,
            num_images,
        )
        return [str(p.resolve()) for p in existing[:num_images]]

    logger.info(
        "Generating %d class images for prompt '%s' -> %s",
        num_images,
        class_prompt,
        output_dir,
    )

    saved_paths: list[str] = []
    images_generated = 0

    while images_generated < num_images:
        current_batch = min(batch_size, num_images - images_generated)
        batch_seed = seed + images_generated

        generator = torch.Generator(device="cpu").manual_seed(batch_seed)

        with torch.no_grad():
            result = pipeline(
                prompt=[class_prompt] * current_batch,
                num_inference_steps=num_inference_steps,
                guidance_scale=guidance_scale,
                generator=generator,
            )

        for img in result.images:
            file_name = f"class_{images_generated:05d}.png"
            file_path = output_path / file_name
            img.save(str(file_path))
            saved_paths.append(str(file_path.resolve()))
            images_generated += 1

            if images_generated >= num_images:
                break

    logger.info("Class image generation complete. Saved %d images.", len(saved_paths))
    return saved_paths
